FROM amd64/ros:noetic-perception-focal


ARG DEBIAN_FRONTEND=noninteractive
ARG ROS_DISTRO=noetic

WORKDIR /root

# install ORBSLAM3 ROS package

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y ros-noetic-image-geometry ros-noetic-pcl-ros \
    ros-noetic-cv-bridge unzip pkg-config autoconf \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    # Use libvtk5-dev, libgtk2.0-dev in ubuntu 16.04 \
    libvtk7-dev libgtk-3-dev \
    libatlas-base-dev gfortran \
    libparmetis-dev \
    python3-wstool \
    # libtbb recommended for speed: \
    libtbb-dev \
    software-properties-common \
    git \
    build-essential \
    cmake \
    libeigen3-dev \
    ros-${ROS_DISTRO}-hector-trajectory-server \
    ros-${ROS_DISTRO}-rviz \
    python3-catkin-tools \
    python3-pip \
    libopencv-contrib-dev \
    libopencv-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN python3 -m pip install evo

RUN git clone https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    mkdir build && cd build && cmake .. && make -j8 && make install


RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc
RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc


# RUN mkdir -p catkin_ws/src && \
#     cd catkin_ws/src && \
#     git clone https://github.com/thien94/orb_slam3_ros.git && \
#     cd .. && \
#     catkin config \
#       --extend /opt/ros/noetic && \
#     catkin build


# #
# # install RealSenseSDK / RealSense ROS wrapper
# #

# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
# RUN add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -sc) main"

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#         libssl-dev \
#         libudev-dev \
#         libusb-1.0-0-dev \
#         librealsense2-dev \
#         librealsense2-utils \
#         ros-${ROS_DISTRO}-realsense2-camera &&  \
#     rm -rf /var/lib/apt/lists/* && \
#     apt-get clean
