%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

System.SaveAtlasToFile: "map_for_stereo_from_20240603_120008_12_to_20240603_120459_99_merge_SlowRun_SlowBag_ZED2"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 643.5951111267952
Camera1.fy: 642.6656126857330
Camera1.cx: 475.2215406900663
Camera1.cy: 307.4120184196884

Camera1.k1: -0.061606731291039
Camera1.k2: 0.100129900708930
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

Camera2.fx: 645.5637158104681
Camera2.fy: 644.6523115974766
Camera2.cx: 471.2755868675698
Camera2.cy: 304.2698424873490

Camera2.k1: -0.060194715488128
Camera2.k2: 0.097872361377687
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.k3: 0.0

Camera.width: 960
Camera.height: 600


# Camera frames per second 
Camera.fps: 10


# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 65.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.999997871208728,0.00203433733119192,-0.000345035701813647,0.254156200727329,
         -0.00203543221633887,0.999992798382587,-0.00320315448502775,0.000762624622412500,
         0.000338516920252090,0.00320384996296369,0.999994810362389,-0.00111605688001320,
         0.0,0.0,0.0,1.0]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -100.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0

