%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

System.SaveAtlasToFile: "map_for_stereo_from_20240603_120008_12_to_20240603_120459_99_merge_SlowRun_SlowBag_ZED2"

Camera.type: "Rectified"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 1074.47
Camera1.fy: 1074.66
Camera1.cx: 953.89
Camera1.cy: 553.739

Camera1.k1: -0.0914784696385453
Camera1.k2: 0.09640778384615316
Camera1.p1: 0.0006926527085876931
Camera1.p2: 0.0002509315599491622

Camera2.fx: 1070.07
Camera2.fy: 1070.07
Camera2.cx: 962.283
Camera2.cy: 549.886

Camera2.k1: -0.09031396397208252
Camera2.k2: 0.09534066004107361
Camera2.p1: 0.00031383285751180055
Camera2.p2: 2.287079614307283e-05

Camera.width: 1920
Camera.height: 1080

# Camera.newWidth: 1920
# Camera.newHeight: 1080

Camera.newWidth: 480
Camera.newHeight: 270

# Camera frames per second 
Camera.fps: 20

Stereo.b: 0.119731

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 20.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2.0
Viewer.GraphLineWidth: 1.0
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -100.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000.0

