%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
# System.LoadAtlasFromFile: "MapEuRoCMH_StereoImu"

# The store file is created from the current session, if a file with the same name exists it is deleted
# System.SaveAtlasToFile: "MapEuRoCMH_StereoImu"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

# Camera.type: "PinHole"
Camera.type: "Rectified"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 1074.47
Camera1.fy: 1074.66
Camera1.cx: 953.89
Camera1.cy: 553.739

Camera1.k1: -0.0914784696385453
Camera1.k2: 0.09640778384615316
Camera1.p1: 0.0006926527085876931
Camera1.p2: 0.0002509315599491622

Camera2.fx: 1070.07
Camera2.fy: 1070.07
Camera2.cx: 962.283
Camera2.cy: 549.886

Camera2.k1: -0.09031396397208252
Camera2.k2: 0.09534066004107361
Camera2.p1: 0.00031383285751180055
Camera2.p2: 2.287079614307283e-05

Camera.width: 1920
Camera.height: 1080

Camera.newWidth: 480
Camera.newHeight: 270

# Camera frames per second 
Camera.fps: 20

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# Close/Far threshold. Baseline times.
Stereo.ThDepth: 20.0
Stereo.b: 0.119731

# Stereo.T_c1_c2: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: f
#   data: [1.0,0,0,0.119731,
#          0,1.0,0,0,
#          0,0,1.0,0,
#          0,0,0,1.0]


# Transformation from camera 0 to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1, 0, 0, 0.693,
         0, 1, 0, 0.079,
         0, 0, 1, 0.571,
         0, 0, 0, 1.0]

# IMU noise
IMU.NoiseGyro: 0.00010715166296138123 # 1.6968e-04
IMU.NoiseAcc: 0.00019111474100504597 # 2.0000e-3
IMU.GyroWalk: 3.7072628390376134e-06
IMU.AccWalk: 1.6112292047120985e-05 # 3.0000e-3
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -1.7
Viewer.ViewpointZ: 0.8
Viewer.ViewpointF: -500.0
Viewer.imageViewScale: 1.0

